/**
 * Frontend registration payload (camelCase).
 * Mirrors the `registrations` table conceptually; `departmentId` / `courseId` are
 * wizard-only and are not sent in `mapToDatabaseFormat`.
 */
export type RegistrationFormData = {
  firstName: string;
  lastName: string;
  ageRange: string;
  sex: string;
  city: string;
  email: string;
  phone: string;
  status: string;
  educationLevel: string;
  familiarWith3D: string;
  softwareUsed: string[];
  familiarWithPhotoshop: string;
  /** Selected in UI as "Yes" | "No" before mapping to DB `has_graphics_tablet` boolean */
  hasGraphicsTablet: "Yes" | "No" | "";
  tabletBrand: string;
  deviceUsed: string;
  availableDays: string[];
  /** Selected in UI as "Yes" | "No" before mapping to DB `has_internet` boolean */
  hasInternet: "Yes" | "No" | "";
  howHeardAbout: string;
  optInForUpdates: boolean;
};

/**
 * Single row insert into `registrations` (snake_case, matches Supabase columns).
 * `id` and `created_at` are generated by the database.
 *
 * RLS: the anon role may only **INSERT** — never assume SELECT/UPDATE/DELETE work from the browser.
 */
export type RegistrationDatabaseInsert = {
  first_name: string;
  last_name: string;
  age_range: "11-17" | "18-24" | "25-34" | "35+";
  sex: "Male" | "Female";
  city: string;
  email: string;
  phone: string;
  status: "Student" | "Employed" | "Self-Employed" | "Unemployed";
  education_level: string | null;
  familiar_with_3d: "Yes" | "No" | "Learning";
  software_used: string[];
  familiar_with_photoshop: "Yes" | "No" | "Learning";
  has_graphics_tablet: boolean;
  tablet_brand: string | null;
  device_used: "Desktop" | "Laptop" | "Tablet";
  available_days: string[];
  has_internet: boolean;
  how_heard_about:
    | "Social Media"
    | "Friend Referral"
    | "Online Search"
    | "Poster/Flyer"
    | "Radio/TV"
    | "Other";
  opt_in_for_updates: boolean;
  registration_fee: number;
  course_fee: number;
  payment_status: "Pending" | "Paid" | "Partially Paid";
};
